# Site settings
title: Scotten Sound
tagline:
logo-fa-class: fa-gem
description: > # this means to ignore newlines until "baseurl:"
  Scotten Sound is the home of the sound desinger / engineer Oliver Scotten.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scottensound.com" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"